
aliases:
  - &restore-cache
    keys:
      - dependencies-{{ .Branch }}-{{ checksum "package.json" }}
      # Fallback in case checksum fails
      - dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
    key: dependencies-{{ .Branch }}-{{ checksum "package.json" }}

version: 2
jobs:
  test-node-9:
    working_directory: ~/egg-passport-auth0
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run: yarn test
    environment:
      - EGG_PASSPORT_AUTH0_DOMAIN: test.auth0.com
      - EGG_PASSPORT_AUTH0_CLIENT_ID: abc123
      - EGG_PASSPORT_AUTH0_CLIENT_SECRET: secret

  test-node-8:
    working_directory: ~/egg-passport-auth0
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run: yarn test
    environment:
      - EGG_PASSPORT_AUTH0_DOMAIN: test.auth0.com
      - EGG_PASSPORT_AUTH0_CLIENT_ID: abc123
      - EGG_PASSPORT_AUTH0_CLIENT_SECRET: secret

  test-node-6:
    working_directory: ~/egg-passport-auth0
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run: yarn test
    environment:
      - EGG_PASSPORT_AUTH0_DOMAIN: test.auth0.com
      - EGG_PASSPORT_AUTH0_CLIENT_ID: abc123
      - EGG_PASSPORT_AUTH0_CLIENT_SECRET: secret

  lint-and-cov:
    working_directory: ~/egg-passport-auth0
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run: yarn ci
      - run: bash <(curl -s https://codecov.io/bash)
    environment:
      - EGG_PASSPORT_AUTH0_DOMAIN: test.auth0.com
      - EGG_PASSPORT_AUTH0_CLIENT_ID: abc123
      - EGG_PASSPORT_AUTH0_CLIENT_SECRET: secret

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-node-8
      - test-node-6
      - test-node-9
      - lint-and-cov:
          requires:
            - test-node-8
            - test-node-6
            - test-node-9
